//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mozilla User Preferences
        ///
        ////* Do not edit this file.
        /// *
        /// * If you make changes to this file while the application is running,
        /// * the changes will be overwritten when the application exits.
        /// *
        /// * To make a manual change to preferences, you can visit the URL about:config
        /// * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
        /// */
        ///
        ///user_pref(&quot;accessibility.typeaheadfind.flashBar&quot;, 0);
        ///user_pref(&quot;app.update.lastUpdateTime.addon-background-update-timer&quot;, 1334434686);
        ///user_pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFPrefs {
            get {
                return ResourceManager.GetString("FFPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Mozilla User Preferences
        ///
        ////* Do not edit this file.
        /// *
        /// * If you make changes to this file while the application is running,
        /// * the changes will be overwritten when the application exits.
        /// *
        /// * To make a manual change to preferences, you can visit the URL about:config
        /// * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
        /// */
        ///
        ///user_pref(&quot;accessibility.typeaheadfind.flashBar&quot;, 0);
        ///user_pref(&quot;app.update.lastUpdateTime.addon-background-update-timer&quot;, 1334434686);
        ///user_pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFPrefsProxyDisabled {
            get {
                return ResourceManager.GetString("FFPrefsProxyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [General]
        ///StartWithLastProfile=1
        ///
        ///[Profile0]
        ///Name=default
        ///IsRelative=1
        ///Path=Profiles/c6socz9d.default
        ///
        ///.
        /// </summary>
        internal static string FFProfiles {
            get {
                return ResourceManager.GetString("FFProfiles", resourceCulture);
            }
        }
    }
}
